### ISSUE TITLE
🐛 캐러셀에서 텍스트가 표시되지 않는 문제

### ISSUE THREAD

**Issue by thisisthewa2** [bookstore-README/front_bookstore-README#115]
### 👀 버그 설명

```bash
/test/carouselTest page 로 이동 또는 <Carousel data={carouselMockData} responsive={responsive} /> 사용 시 이미지는 표시되나 텍스트가 표시 되지 않는 문제
```

### ⎙ 스크린샷

<img width="988" alt="스크린샷 2024-02-05 오전 12 45 37" src="https://github.com/bookstore-README/front_bookstore-README/assets/119280160/cbea7150-a21a-4f6c-a099-f0ae239392a8">

### Browsers

None

### OS

None

**Comment by yunajoe** [comment]
저 issue는 제가 아니라 previewInfo 컴퍼넌트에서 처리를 해야되는 겁니다 . 
previewInfo 컴퍼넌트가 제 캐러셀 이미지 크기를 고려하지 않아서 issue가 생긴거예요. ! 이 부분 수정해주시면 될 것 같습니다
