### ISSUE TITLE
💢 카테고리 api 활용 및 카테고리 페이지 url 문제

### ISSUE THREAD

**Issue by hongjw030** [bookstore-README/front_bookstore-README#182]
## ❤ 개요

현재 카테고리 라우팅이 비효율적인 부분이 있어 카테고리 페이지 url을 바꾸면 어떨까 싶습니다. 
이에 대해 팀원분들 의견(+조언)을 듣고자 이슈 팝니다!

한줄요약: 
**지금 url은 localhost:3000/domestic/novel 이런 식인데 이걸 localhost:3000/0/3 이렇게 바꾸자.**

## 🧡문제상황 

현재 카테고리 데이터는 아래와 같이 구성돼있습니다. 
```
// 국내 건강/스포츠 카테고리
{
  categoryId: 1
  mainId: 0
  subId: 1
  link: "/healthsport"
}
```

만약 내가 국내 건강/스포츠 카테고리에 있다면 아래 사진 sidebar 컴포넌트에서는 건강/스포츠 카테고리가 초록색으로 표시되기 위해 다음 과정을 거칩니다.
1. useRouter로 현재 url 경로를 떼온다. 여기선 localhost:3000/domestic/healthsport일 것임.
2. url pathname 마지막 부분 healthsport을 떼어와 domesticCategoryList 배열을 for문으로 돌아 healthsport 속성이 들어있는 객체를 찾고, 해당 카테고리를 초록색으로 표시해줍니다. (걍 for문 30번 돌아서 내가 뭔 카테고리에 있는지 찾는단 뜻)

![image](https://github.com/bookstore-README/front_bookstore-README/assets/89698149/3ce46598-05f4-49d9-a023-d92f654e9ea7)

지금 당장은 카테고리 수가 30개밖에 안되니 별 상관은 없지만, 로직 자체가 비효율적이긴 합니다. 

## 💛 제 의견 

제가 제안하는 로직은 다음과 같습니다!!!

국내 건강/스포츠 카테고리로 접근 시, 예를 들어 건강/스포츠 카테고리의 categoryId가 2라면

1. localhost:3000/domestic/2 로 url이 이동되게 함.
2. 서버로부터 받아온 domesticCategoryList든, 기존 프론트단에 저장되어있는 categoryList든 하여간 categoryList[2] 로 접근하면 바로 해당 객체를 찾을 수 있음.
3. for문 돌릴 필요 없이 해당 객체에 초록색 스타일을 입히면 됨.

## 💚 주의할 점
- 일 사이즈 자체는 크지 않을거.. 걸요..? 일단 sidebar나 header의 category tab 단에서만 수정하면 돼서 다른 파트와 충돌날 일은 없을거 같습니다
- 이렇게 되면 로직 자체는 효율적이지만, url은 보기 힘들어지는 단점이 있습니다.
- 다만 카테고리 api를 활용하려면 이렇게 categoryId나 mainId, subId 같은 id 숫자 값을 url에 바로 때려박는 식도 나쁘지 않을 거 같아 건의해봅니당. u.u

**Comment by orrhrr** [comment]
1) response로 받아온 mainId, subId를 인덱스로 사용하는 배열필요

![스크린샷 2024-02-08 오후 9 03 10](https://github.com/bookstore-README/front_bookstore-README/assets/120437902/0e4b9e8b-c3fe-4002-8105-21bae56981d0)

2) 받아온 response에서 subId를 추출해 배열에서 매칭되는 데이터를 찾음
3) 사용하는 곳에서 CATEGORY_MAIN_ID[mainId], CATEGORY_SUB_ID[subId] 이런식으로 불러와서 사용

요렇게 하면 안되려나용??

```
 {categoryList.map((el, index) => {
        // 현재 카테고리가 선택된 카테고리와 일치하는지 확인
        const isSelected = CATEGORY_SUB_ID[subId] === el.link;
        return (
          <Link
            className={`block text-[13px] ${isSelected ? 'font-bold text-green' : 'text-gray-2'}`}
            href={`/${isDomestic ? 'domestic' : 'foreign'}${el.link}${pageName ? `/${pageName}` : ''}`}
            key={index}>
            {el.title}
          </Link>
        );

```
요런식으루용..

코드를 보니 createReadMeGenre 함수로 {title:string , selected: boolean}형태의 객체로 받고있는것 같은데,
```
const CATEGORY_ARRAY = [
  { title: '가정/원예', selected: boolean },
  { title: '건강', selected: boolean },
  { title: '시/소설', selected: boolean },
];
```
selected이 어떻게 활용되고 있는지 잘 모르겠지만 ㅠㅠ
이렇게 배열로 만들면 subId도 받아서 index로 활용할 수 있을것 같긴합니당
그러면 30번을 안돌아도 되지않을까용? 카테고리 추가되면 배열에 하나 더 넣으면 될거같구용...
부조칸 설명 죄송함댜 또릅
url 주소는 지금이 좀더 사용자입장에선 좋을것 같아서용....(윤진님의 광기어린 네이밍 노고도 녹아있뜸..)

**Comment by hongjw030** [comment]
> 1. response로 받아온 mainId, subId를 인덱스로 사용하는 배열필요
> 
> ![스크린샷 2024-02-08 오후 9 03 10](https://private-user-images.githubusercontent.com/120437902/303319910-0e4b9e8b-c3fe-4002-8105-21bae56981d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NDcyNjksIm5iZiI6MTcwNzQ0Njk2OSwicGF0aCI6Ii8xMjA0Mzc5MDIvMzAzMzE5OTEwLTBlNGI5ZThiLWMzZmUtNDAwMi04MTA1LTIxYmFlNTY5ODFkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQwMjQ5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTcyYmY3YTkwOWU4Zjc2MzA4ODI1YmNmZjhiNDc3ZmEwMjRkZDk4YjgxOTczYTRmOGQyN2UxNGUyZDc3MzU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._n3n5f15QSKs9nVjErFXEIbM6CTbQLQWvALmYdqrLDs)
> 
> 2. 받아온 response에서 subId를 추출해 배열에서 매칭되는 데이터를 찾음
> 3. 사용하는 곳에서 CATEGORY_MAIN_ID[mainId], CATEGORY_SUB_ID[subId] 이런식으로 불러와서 사용
> 
> 요렇게 하면 안되려나용??
> 
> ```
>  {categoryList.map((el, index) => {
>         // 현재 카테고리가 선택된 카테고리와 일치하는지 확인
>         const isSelected = CATEGORY_SUB_ID[subId] === el.link;
>         return (
>           <Link
>             className={`block text-[13px] ${isSelected ? 'font-bold text-green' : 'text-gray-2'}`}
>             href={`/${isDomestic ? 'domestic' : 'foreign'}${el.link}${pageName ? `/${pageName}` : ''}`}
>             key={index}>
>             {el.title}
>           </Link>
>         );
> ```
> 
> 요런식으루용..
> 
> 코드를 보니 createReadMeGenre 함수로 {title:string , selected: boolean}형태의 객체로 받고있는것 같은데,
> 
> ```
> const CATEGORY_ARRAY = [
>   { title: '가정/원예', selected: boolean },
>   { title: '건강', selected: boolean },
>   { title: '시/소설', selected: boolean },
> ];
> ```
> 
> selected이 어떻게 활용되고 있는지 잘 모르겠지만 ㅠㅠ 이렇게 배열로 만들면 subId도 받아서 index로 활용할 수 있을것 같긴합니당 그러면 30번을 안돌아도 되지않을까용?� 카테고리 추가되면 배열에 하나 더 넣으면 될거같구용... 부조칸 설명 죄송함댜 또릅 url 주소는 지금이 좀더 사용자입장에선 좋을것 같아서용....(윤진님의 광기어린 네이밍 노고도 녹아있뜸..)

확실히 사용자 입장에서는 지금처럼 문자열로 이루어진 url 주소가 나을 거 같긴해요, ㅇ0ㅇ 의견 감사합니다!!! 그럼 흠... 카테고리 main id와 sub id를 가지고 배열 위치를 계산하는 utils 함수를 만들어 진행해도 ㄷ좋을 거 같네요!!! 의견 감사합니다!! u.u
