### ISSUE TITLE
🐛 사이드바 링크에 접속할 때 /category 페이지로만 접근 가능한 문제

### ISSUE THREAD

**Issue by hongjw030** [bookstore-README/front_bookstore-README#99]
### 👀 버그 설명

베스트셀러 페이지, 카테고리 페이지, 신간페이지에서 공통으로 사용하는 사이드바 컴포넌트입니다.

![image](https://github.com/bookstore-README/front_bookstore-README/assets/89698149/26cedb54-1e9e-4fff-a1f7-3260c6a37c99)

## 문제 상황

현재는 카테고리 페이지의 사이드바 컴포넌트를 클릭해서 /국내/과학 링크로 접속하려 할 때, /domestic/science 링크로만 접근이 가능합니다.

근데 사이드바 컴포넌트는 신간, 베스트셀러 등 다른 페이지에서도 사용할 수 있는 컴포넌트입니다. 이 상태 그대로 SidebarLayout을 신간, 베스트셀러 페이지에 적용하게 된다면, 신간 페이지에서 국내/과학 카테고리를 눌렀을 때 /newest/domestic/science 페이지가 아니라 /domestic/science 페이지로 넘어가게 됩니다. 

## 해결방안 1

**지금 pages 폴더 내 구조를 바꾸지 않고, Link href 주소만 바꾸는 방법**

베스트셀러 페이지에서 국내/과학 을 클릭하면 bestseller/domestic/scicence, 
신간 페이지에서 외국/소설을 클릭하면 newest/foreign/fiction 으로 이동하게끔 링크를 수정해야 합니다.
이렇게 하려면 useRouter.pathname 전체를 받아 `/` 를 기준으로 파싱하여 현재 페이지 위치를 파악해야 하는 단점이 있음.

## 해결방안 2

**pages 폴더 구조 자체를 뒤엎는 방법**

카테고리페이지에서 국내/과학 페이지 접근 시
category?main=domestic&sub=science,
베스트 페이지에서 외국/전체보기 페이지 접근시
best?main=foreign 

이런 식으로 페이지 라우팅을 하기위해, pages 폴더 내부를 다음과 같이 수정해야 합니다.
```
pages
ㄴbestsellers
ㄴcategory
ㄴnewest
...
```

그리고 best, category, newest 페이지 내부에서 쿼리문을 해석해야 합니다.

```js
// 예시, pages/category/index.tsx 파일

import {useRouter} from 'react';

export default function CategoryPage(){
  const router = useRouter();
  const {main, sub} = router.query; // main에는 국내 외국 값이 들어감, sub에는 과학, 예술, 소설 등 하위 값이 들어감.

  ....
}
```

### Browsers

None

### OS

None

**Comment by orrhrr** [comment]
개인적으로는 폴더구조를 변경하는게 더 좋아보입니다.
1) 확장성이 좋아보임
2) 코드로 해결해야 하는 부분이 줄어듦
3) ~~url이 간지나보임~~


근데 폴더구조 변경에 적어주신 예시를 잘 이해를 못했어요 ㅠㅠ
<img width="307" alt="스크린샷 2024-02-03 오후 8 33 06" src="https://github.com/bookstore-README/front_bookstore-README/assets/120437902/bbfa3d37-9cc2-42bb-ad97-232e2ed305a5">

요런식으로 가는건 어떨까용?

**Comment by thisisthewa2** [comment]
재원님은 국내 > 베스트셀러, 신간 > 가정원예 , 소설.. + 국내 > 가정원예, 소설 이런 폴더구조를 생각하신 것 같아요! (맞나요??) 전 승연님이 적어주신 구조가 더 맘에 드네요. 조금 더 직관적이고 승연님 방식대로면 현재의 폴더 구조를 크게 수정하지 않으면서 domestic/[category] (다이나믹 라우팅) 아래에 /best /newest 만 추가해도 될 것 같아요. 추가적으로 domestic/[category]/index엔 해당 분야 전체 책을 두고, domestic/index 국내 분야 전체 책을 두면 어떨까요?

**Comment by hongjw030** [comment]
다들 의견 감사합니다!!!!! 윤진님 말씀대로 저는 신간, 베스트셀러 페이지 각각 카테고리를 두는 방식을 생각했는데요

그럼 승연님께서 말씀하시는 폴더 구조가 아래 구조 같은 게 맞을까요???

```
[pages]
ㄴ[domestic]
    ㄴindex.tsx // 국내/전체 페이지
    ㄴ{categoryId}.tsx // 국내 / 과학 페이지
    ㄴ[bestseller]
        ㄴindex.tsx // 국내/베스트셀러/전체 페이지
        ㄴ{categoryId}.tsx // 국내/베스트셀러/과학 페이지
    ㄴ[newest]
        ㄴindex.tsx // 국내/신간/전체 페이지
        ㄴ{categoryId}.tsx // 국내/신간/과학 페이지
ㄴ[foreign]
    ㄴindex.tsx // 외국/전체 페이지
    ㄴ{categoryId}.tsx // 외국/ 과학 페이지
    ㄴ[bestseller]
        ㄴindex.tsx // 외국/베스트셀러/전체 페이지
        ㄴ{categoryId}.tsx // 외국/베스트셀러/과학 페이지
    ㄴ[newest]
        ㄴindex.tsx // 외국/신간/전체 페이지
        ㄴ{categoryId}.tsx // 외국/신간/과학 페이지
```

pages 폴더 구조를 갈아엎는 거라 충돌이 엄청날거 같아서 ㅋㅋ ㅠㅠㅠ 일단 다른 팀원님들 의견도 다 듣고 한번 시간 정해서 확 고쳐놔야겠어용 ;D

**Comment by thisisthewa2** [comment]
전 승연님이 말씀하신 구조는 아래 같다고 생각했어요! 그러니까 베셀/신간이 각 카테고리 id 마다 하나씩 있는거죠. 재원님이 제안하시는 것은 베스트/신간 아래에 카테고리 분류가 들어가는 것이고, 승연님이 제안하시는 것은 카테고리 분류 아래에 베스트/신간이 위치하는 거죠. (맞나요?)
<img width="479" alt="스크린샷 2024-02-04 오전 3 01 58" src="https://github.com/bookstore-README/front_bookstore-README/assets/119280160/7fcec354-1d7f-4d9e-982e-6fd2a7fdddad">

**Comment by orrhrr** [comment]
```
[pages]
 ㄴ[domestic]
   ㄴindex.tsx //국내전체
   ㄴ[bestSeller]
      ㄴindex.tsx// 국내/전체/베스트
   ㄴ[newest]
      ㄴindex.tsx // 국내/전체/신간
   ㄴ[caregoryId]
      ㄴindex.tsx // 국내/카테고리/전체
      ㄴ[bestseller]
        ㄴindex.tsx // 국내/카테고리/베스트셀러
      ㄴ[newest]
        ㄴindex.tsx// 국내/카테고리/신간
 ㄴ[foreign]
   ㄴindex.tsx
   ㄴ[bestSeller]
      ㄴindex.tsx
   ㄴ[newest]
      ㄴindex.tsx
   ㄴ[caregoryId]
      ㄴindex.tsx
      ㄴ[bestseller]
        ㄴindex.tsx
      ㄴ[newest]
        ㄴindex.tsx
```

저는 요런식으로 생각해써용! 아마 윤진님이 말씀하신것과 같은거 같은데...
카테고리를 우선적으로 경로설정하고, 그에 맞게 페이지를 각 카테고리의 하위로 넣어두는거에용
이렇게 되면 예를 들어서 국내/과학도서에 이벤트 페이지가 있다면
국내->과학->이벤트페이지(새폴더 생성) 요롷게 계속 만들어갈수있을것 같아서용ㅎㅎ
